# Generated by Django 4.2.1 on 2023-06-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_author_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Germany', 'Germany'), ('Germany', 'Germany'), ('English', 'English')], max_length=10)),
            ],
        ),
    ]
