# Generated by Django 4.2.1 on 2023-06-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Select a Language for this book', to='catalog.language'),
        ),
    ]
