# Generated by Django 4.2.1 on 2023-06-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='language',
        ),
        migrations.AddField(
            model_name='language',
            name='choice_language',
            field=models.CharField(choices=[('Germany', 'Germany'), ('Germany', 'Germany'), ('English', 'English')], default='English', help_text='Enter a book language', max_length=10),
        ),
    ]
