# Generated by Django 4.2.1 on 2023-06-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_language_language_language_choice_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='choice_language',
            field=models.CharField(help_text='Enter a book language', max_length=10),
        ),
    ]
