# Generated by Django 4.2.1 on 2023-06-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_book_language_book_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='language',
            name='choice_language',
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(default='EN', help_text='Enter a book language', max_length=200),
        ),
    ]
