# Generated by Django 4.2.1 on 2023-08-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
